# Package mappings for the installer
packages:
  git:
    apt:
      name: git
    brew:
      name: git
    dnf:
      name: git
  gpg:
    apt:
      name: gnupg2 # Debian/Ubuntu often use gnupg2
    brew:
      name: gnupg
    dnf:
      name: gnupg2
  neovim:
    apt:
      name: neovim
    brew:
      name: neovim
    dnf:
      name: neovim
  zsh:
    apt:
      name: zsh
    brew:
      name: zsh
    dnf:
      name: zsh
  build-essential:
    apt:
      name: build-essential
    dnf:
      name: "Development Tools"
      type: group
    # Note: Other package managers would define their equivalents here
  curl:
    apt:
      name: curl
    brew:
      name: curl
    dnf:
      name: curl
  file:
    apt:
      name: file
    brew:
      name: file
    dnf:
      name: file
  procps:
    apt:
      name: procps
    dnf:
      name: procps-ng
